services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mahou\MosparoPowermail\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Mahou\MosparoPowermail\FormNormalizer\PowermailFormNormalizer:
        tags:
            - { name: 'mosparo.form_normalizer' }
